[package]
name = "game"
version = "0.3.0"
edition = "2018"

[dependencies]
heapless = "0.7"

[dependencies.nanorand]
version = "0.7"
default-features = false
features = [
    "std",
    "tls",
    "wyrand",
]
